#!/bin/bash
#
# phegetrun
#
# Clean, build and start server


# Stop on errors, print commands
set -e

# Set environment variables
export FLASK_DEBUG=True
export FLASK_APP=pheget
export PHEGET_SETTINGS=config.py

# Run the development server on port 8000
flask run --host 0.0.0.0 --port 8000
